### ISSUE TITLE
Create Etherpad for Workshop

### ISSUE THREAD

**Issue by sdhutchins** [U-BDS/2023-12-14-uab#3]
TBD if we want to do this, but it could be helpful

- [x] https://pad.carpentries.org/

**Comment by atrull314** [comment]
I don't think it'd be bad to do. Help with attendance at minimum: https://pad.carpentries.org/2023-12-14-uab

**Comment by sdhutchins** [comment]
Added in https://github.com/U-BDS/2023-12-14-uab/commit/371c88561a15784eb57fa91a98e595cc44e129b1
